#!/bin/sh

# Up here works best for things that exit early
if [ "$1" = "healthz" ]; then
  check=$(ps -p $(cat tmp/pids/server.pid)|grep ruby|awk '{print $4}')
  if [ "$check" = "ruby" ]; then
    echo "SUCCESS"
    exit 0
  else
    echo "FAILURE"
    exit 1
  fi
fi

### PREAMBLE
echo "==> Launched ENTRYPOINT"
echo ">>> Chase Securities Automated Platform Deployment <<<"
echo ">>>  This could take a while. Sit back, and relax  <<<"
echo ">>>            We'll take it from here.            <<<"

. /bin/envsetup

echo "==> Bootstrap Complete!"
if [ "$1" = "rails" ]; then
  echo "==> Tailing logs"
  tail -f log/*.log &
  echo "==> Rolling out Rails on $openshift_host"
  bundle exec rails server -b 0.0.0.0 -p 3000
fi

if [ "$1" = "dns" ]; then
  echo "==> Rolling out Sidekiq on $openshift_host"
  bundle exec rails runner "workers/${2}.rb"
fi

